### ISSUE TITLE
Extra credit: store images in DB, instead of URL

### ISSUE THREAD

**Issue by sesm** [Transet/Web-Technologies_site#13]
Figure out how to store base64-encoded images in DB
Figure out how to send binary data in XMLHttpRequest (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)
Use browser's native 'open file' control to select image.

**Comment by Transet** [comment]
It was difficult but I did this.

**Comment by Transet** [comment]
resolved

**Comment by sesm** [comment]
Congratulations on your 10!
Some final tips for you: 
- you don't have to make one more request to get the last id, you can just return id in a response to the first request.
- you had wrong dependencies in package.json ('sqlite' instead of 'sqlite3')
- addNdel.js:57 - you are wrong, we can query dynamically added elements. For example, try this in browser console:

```
var newDiv = document.createElement('div');
newDiv.className = 'uniqueClass';
document.querySelector('body').appendChild(newDiv);
document.querySelector('.uniqueClass');
```
- Your JS code is really messy: inaccurate function names, a lot of duplicated code, some unused code. At real work such code will likely be rejected. Look at your code closer and try to refactor it, should be 2-3 times smaller.

**Comment by Transet** [comment]
Thanks for the advice. I got it.
