### ISSUE TITLE
Add sqlite3 to dependencies in package.json

### ISSUE THREAD

**Issue by sesm** [Transet/Web-Technologies_site#15]
Add sqlite3 to dependencies in package.json
Hint: 'npm install --save' automatically upates package.json

**Comment by Transet** [comment]
keep tracking this issue in order to add other dependencies if they exist.

**Comment by sesm** [comment]
I don't think you will ever need other dependencies. The task is to use as few libraries as possible.

**Comment by Transet** [comment]
Ok.
Mark as resolved.
