### ISSUE TITLE
Extra credit: show mobile version (i.e. no left menu) on mobile browsers

### ISSUE THREAD

**Issue by sesm** [Transet/Web-Technologies_site#6]
Figure out how mobile browsers work, and what is 'meta name="viewport"' (https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag)
Set viewport, so that mobile browsers display small width version, instead of big width version with scrolling.
Use Chrome and IE device emulator to test.

**Comment by Transet** [comment]
Made several rules for mobile devices.
Works as designed in emulator.
@sesm Could you explain what you really want from this issue?

**Comment by sesm** [comment]
@Transet let me check how it works now, maybe what you've already done is enough.

**Comment by sesm** [comment]
Looks good.
